filetype plugin indent on
syntax off
set nonumber
set tabstop=4        
set shiftwidth=4    
set expandtab      
set splitright
set splitbelow
set showmatch
set incsearch       
set clipboard=unnamedplus








